### ISSUE TITLE
Can't login in debian image.

### ISSUE THREAD

**Issue by Kuinox** [godarch/distributions#4]
Hi,
Maybe i missed something, but i can't login in the debian image.  
Debian doesn't allow default password for root, i don't know what to do.  
Thanks for this great thing, will have a lot of fun.

**Comment by pauldotknopf** [comment]
The default install doesn't have a password assigned to ```root```, you are correct.

You just got to give it a password.

See [here](https://github.com/pauldotknopf/darch-recipes/blob/4956459d1001ff875bb4f9add8ce0e4f161ac160/recipes/base-common/script#L20).

**Comment by Kuinox** [comment]
Thanks !  
So basically, i can't log in , if i don't build it myself.  
The docs should indicate this for future users, no ?  
Also, what if i pull an image from someone else ?
